config/routes.rb
Rails.application.routes.draw do
  root to: "candidates#index"
  resources :candidates do
  resources :issues
end
end 

app/models/candidate.rb
class Candidate < ActiveRecord::Base
  validates_presence_of :first_name
  validates_presence_of :last_name
  has_many :issues, dependent: :destroy
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :candidate
  after_initialize :set_defaults, unless: :persisted?
# The set_defaults will only work if the object is new

def set_defaults
  self.immigration  ||= ''
  self.net_neutrality  ||= ''
  self.climate_change ||= ''
  self.gun_control   ||= ''
  self.intellectual_property  ||= ''
  self.marijuana  ||= ''
  self.election_cycle   ||=2016
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    # @client = Congress::Client.new(ENV["CONGRESS_SECRET_KEY"])
    @candidates = Candidate.all

  end

  def show
    @candidate = Candidate.find(params[:id])
  end

  def new
    @candidate = Candidate.new
  end
  def create
    @candidate = Candidate.create(candidate_params)
    redirect_to @candidate
  end

  def destroy
    @candidate = Candidate.find(params[:id])
    @candidate.destroy
    redirect_to candidates_path
  end
  def edit
    @candidate = Candidate.find(params[:id])
  end
  def update
    @candidate = Candidate.find(params[:id])
    @candidate.update(candidate_params)
    redirect_to @candidate
  end

  private
  def candidate_params
    params.require(:candidate).permit(:first_name, :last_name, :party, :jurisdiction, :incumbent)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
  @candidate = Candidate.find(params[:candidate_id])
  end

  # new
  def new
    @candidate = Candidate.find(params[:candidate_id])
    @issue = Issue.new
  end

  # create
  def create
    @candidate = Candidate.find(params[:candidate_id])
    @issue = @candidate.issues.create(issue_params)
    redirect_to candidate_path(@candidate)
  end

  #show
  def show
    @issue = Issue.find(params[:id])
  end

  # edit
  def edit
    @issue = Issue.where(candidate_id: params[:id]).take
  end

  # update
  def update
    @issue = Issue.find(params[:id])
    @issue.update(issue_params)

    redirect_to issues_path(@issue)
  end

  # destroy
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    redirect_to candidates_path
  end

  private
  def issue_params
    params.require(:issue).permit(:immigration, :net_neutrality, :climate_change, :gun_control, :intellectual_property, :marijuana, :election_cycle, :candidate_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_form.html.erb
<ul><%= form_for @candidate do |f| %></ul>
<ul><%= f.label :first_name%></ul>
<ul><%= f.text_field :first_name%></ul>
<ul><%= f.label :last_name%></ul>
<ul><%= f.text_field :last_name%></ul>
<ul><%= f.label :jurisdiction%></ul>
<ul><%= f.text_field :jurisdiction%></ul>
<ul><%= f.label :party%></ul>
<ul><%= f.text_field :party%></ul>
<ul><%= f.label :photo_url, style: 'display:none' %></ul>
<ul><%= f.text_field :photo_url, style: 'display:none' %></ul>
<ul><%= f.label :bioguide_id, style: 'display:none' %></ul>
<ul><%= f.text_field :bioguide_id, style: 'display:none' %></ul>
<ul><%= f.label :incumbent %></ul>
<ul><%= f.check_box :incumbent%></ul>
<ul><%= f.submit %></ul>
<% end %>

app/views/candidates/edit.html.erb
<ul><%= render "form" %></ul>

app/views/candidates/index.html.erb
<h1 class="name">Candidate Score</h1>

<%= image_tag "politics.jpg", :class => "politics_images" %>

<%= button_to "Add A New Candidate", new_candidate_path, :method => :get %>
<ul>
  <% @candidates.each do |candidate| %>
  <li>
    <%= link_to "#{candidate.first_name} #{candidate.last_name}", candidate_path(candidate) %>
  </li>
  <% end %>
</ul>

app/views/candidates/new.html.erb
<p class="name">Import a Candidate from Sunlight Foundation</p>
<label>State <input id="state" type="text"></label>

<ul id="output">

</ul>

<ul><button>Submit</button></ul>

<p class="name">Manually add a Candidate</p>
<ul><%= render "form" %></ul>
<img src="..." alt="Candidate Photo" id='my_img' height="275" width="225">

app/views/candidates/show.html.erb
<h2><%= @candidate.first_name %>
<%= @candidate.last_name %>
</h2>
<%= "<img src='#{@candidate.photo_url}' alt='Candidate Photo' height='275' width='225'>" unless @candidate.photo_url %>
<h3><%= @candidate.party %></h3>
<h4>
<%= @candidate.jurisdiction %>
</h4>
<p>
  This candidate is
  <%= "not" unless @candidate.incumbent %>
  an incumbent.
</p>
<h3>Issue Profile</h3>
<ul>
  <% @candidate.issues.each do |issue| %>
    <li><%= "Election Cycle: #{issue.election_cycle}" %></li>
    <li><%= "Immigration: #{issue.immigration}" %></li>
    <li><%= "Net Neutrality: #{issue.net_neutrality}" %></li>
    <li><%= "Climate Change: #{issue.climate_change}" %></li>
    <li><%= "Gun Control:  #{issue.gun_control}" %></li>
    <li><%= "Intellectual Property: #{issue.intellectual_property}" %></li>
    <li><%= "Marijuana #{issue.marijuana}" %></li>
  <% end %>
  <% if @candidate.issues.size ==0 %>
    <li><%= "No Issue Profile on Record" %></li>
  <% end %>
</ul>

<p> <ul><%= button_to "Edit Candidate", edit_candidate_path(@candidate), :method => :get %></ul>
  <% if @candidate.issues.size ==0 %>
  <ul>  <%= button_to "Add Issue Profile", new_candidate_issue_path(@candidate), :method => :get %></ul>
  <% else %>
  <ul>  <%= button_to "View Issue Profile", candidate_issues_path(@candidate), :method => :get %></ul>
  <% end %>


<ul><%= button_to "View Other Candidates", candidates_path, :method => :get %></ul>
<ul><%= button_to "Delete Candidate", candidate_path(@candidate), :method => :delete %></ul>
</p>

app/views/issues/_form.html.erb
<ul><%= form_for [@candidate, @issue] do |f| %></ul>
<ul><%= f.label :immigration%></ul>
<ul><%= f.text_field :immigration%></ul>
<ul><%= f.label :net_neutrality%></ul>
<ul><%= f.text_field :net_neutrality%></ul>
<ul><%= f.label :climate_change %></ul>
<ul><%= f.text_field :climate_change%></ul>
<ul><%= f.label :gun_control%></ul>
<ul><%= f.text_field :gun_control%></ul>
<ul><%= f.label :intellectual_property%></ul>
<ul><%= f.text_field :intellectual_property%></ul>
<ul><%= f.label :marijuana%></ul>
<ul><%= f.text_field :marijuana%></ul>
<ul><%= f.label :election_cycle%></ul>
<ul><%= f.text_field :election_cycle%><ul>
<ul><%= f.submit %></ul>
<% end %>

app/views/issues/edit.html.erb
<ul>Edit Candidate Issue Profile</ul>

<ul><%= render "form" %></ul>

app/views/issues/index.html.erb
<!--
<p>
  candidates_path: <%=candidates_path%>
  </p>
  candidate_path(@candidate): <%=candidate_path(@candidate)%>
  <p>
      candidate_issues_path: <%=candidate_issues_path(@candidate)%>
    </p> -->



    <ul>
      <% @candidate.issues.each do |issue| %>
        <li><%= "Election Cycle: #{issue.election_cycle}" %></li>
        <li><%= "Immigration: #{issue.immigration}" %></li>
        <li><%= "Net Neutrality: #{issue.net_neutrality}" %></li>
        <li><%= "Climate Change: #{issue.climate_change}" %></li>
        <li><%= "Gun Control:  #{issue.gun_control}" %></li>
        <li><%= "Intellectual Property: #{issue.intellectual_property}" %></li>
        <li><%= "Marijuana #{issue.marijuana}" %></li>
      <% end %>
      <% if @candidate.issues.size ==0 %>
        <li><%= "No Issue Profile on Record" %></li>
      <% end %>
    </ul>

app/views/issues/new.html.erb
<p class="name">Add Candidate Issue Profile</p>


<ul><%= render "form" %></ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
  <!-- <script type="text/javascript" src="app/assets/javascripts/main.js"></script> -->
  <title>Scorecard</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>